//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discografia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.discogs.com")]
        public string DiscogsBaseURL {
            get {
                return ((string)(this["DiscogsBaseURL"]));
            }
            set {
                this["DiscogsBaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("discografia.mx/1.0")]
        public string DiscogsUserAgent {
            get {
                return ((string)(this["DiscogsUserAgent"]));
            }
            set {
                this["DiscogsUserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DXOHuxEAoxtmsQEKXkFn")]
        public string DiscogsConsumerKey {
            get {
                return ((string)(this["DiscogsConsumerKey"]));
            }
            set {
                this["DiscogsConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YjwtZniyLIiCRPCMfVCriLUKdybHnFxX")]
        public string DiscogsConsumerSecret {
            get {
                return ((string)(this["DiscogsConsumerSecret"]));
            }
            set {
                this["DiscogsConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/releases/")]
        public string DiscogsGetReleaseUri {
            get {
                return ((string)(this["DiscogsGetReleaseUri"]));
            }
            set {
                this["DiscogsGetReleaseUri"] = value;
            }
        }
    }
}
